#zk:
#    url: 127.0.0.1:2181
#    timeout: 1000
#    retry: 3
spring:
    cloud:
        nacos:
            discovery:
#                server-addr: 127.0.0.1:8848
                enabled: false
                register-enabled: false
            config:
                enabled: false
    application:
        name: source
    datasource:
#        url: jdbc:mysql://49.235.221.50/batch_message?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        url: jdbc:mysql://121.4.78.71/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: liubenwei
        password: liubenwei
    servlet:
        multipart:
            max-file-size: 5MB
            max-request-size: 10MB

server:
    port: 6060
mybatis:
    mapper-locations: classpath*:mapper/*.xml
    type-aliases-package: com.liu.sourceProject.easyExcel.entity
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
